-- Generated by extract_feed_pricing_from_xlsx.py
TRUNCATE feed_fx_rates CASCADE;
INSERT INTO feed_fx_rates (country_code, country_name, currency_code, rate_per_usd, peg_type, notes)
VALUES
('AE', 'UAE', 'AED', 3.6725, 'Hard Peg', 'Stable'),
('BH', 'Bahrain', 'BHD', 0.376, 'Hard Peg', 'Stable'),
('KW', 'Kuwait', 'KWD', 0.307, 'Basket Peg', 'Stable'),
('QA', 'Qatar', 'QAR', 3.64, 'Hard Peg', 'Stable'),
('SA', 'Saudi Arabia', 'SAR', 3.75, 'Hard Peg', 'Stable'),
('OM', 'Oman', 'OMR', 0.385, 'Hard Peg', 'Stable'),
('JO', 'Jordan', 'JOD', 0.709, 'Hard Peg', 'Stable'),
('PS', 'Palestine', 'ILS', 3.6, 'Uses ILS', 'Approximate'),
('IL', 'Israel', 'ILS', 3.6, 'Floating', 'Approximate'),
('IQ', 'Iraq', 'IQD', 1310.0, 'Managed', 'Approximate'),
('EG', 'Egypt', 'EGP', 49.0, 'Managed Float', 'Volatile — verify before use'),
('SY', 'Syria', 'SYP', 13100.0, 'Multiple rates', 'Market rate — highly volatile'),
('LB', 'Lebanon', 'USD', 1.0, 'N/A', 'Priced in USD per request'),
('LY', 'Libya', 'USD', 1.0, 'N/A', 'Priced in USD per request'),
('DZ', 'Algeria', 'DZD', 135.0, 'Managed', 'Approximate'),
('MA', 'Morocco', 'MAD', 9.8, 'Basket Peg', 'Approximate'),
('TN', 'Tunisia', 'TND', 3.1, 'Managed Float', 'Approximate'),
('YE', 'Yemen', 'YER', 250.0, 'Floating', 'Highly volatile'),
('SD', 'Sudan', 'SDG', 600.0, 'Floating', 'Highly volatile');