-- Generated by extract_notification_tasks_from_xlsx.py
TRUNCATE notification_task_definitions CASCADE;

INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  'd6089ac3-1305-5eeb-a7e3-debcf61526d6', 1, 'Nutrition', NULL, NULL, 'Recommended Feed in Inventory', 'Inventory',
  'Reminder: Please update the feed for {Group Name}', 'Update {Group Name} Feed', 'تذكير: الرجاء تحديث العلف لاسم المجموعة {اسم المجموعة}', 'تحديث علف {اسم المجموعة}',
  'Please update the existing feed with xx kg of Recommmended Product', 'الرجاء تحديث العلف الحالي بـ {xx} كغ من المنتج الموصى به', 'GroupName', 'Accept Product', NULL,
  'Next Day', 'USER', 'MEDIUM', NULL, NULL, ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  'ea0cee35-e45b-5a60-aa8f-f7aa1ee53355', 2, 'Nutrition', NULL, NULL, 'Recommended Feed in from Market Products', 'Inventory',
  'Reminder: Please purchase  {Recommmended Product} for {Group Name}', 'Buy {Recommended Product}', 'تذكير: الرجاء شراء {المنتج الموصى به} لاسم المجموعة {اسم المجموعة}', 'شراء {المنتج الموصى به}',
  'Please purchase {Recommmended Product} for {Group Name} and add to the Current Feed Inventory', 'الرجاء شراء {المنتج الموصى به} لاسم المجموعة {اسم المجموعة} وإضافته إلى مخزون الأعلاف الحالي', NULL, 'Accept Product', NULL,
  '2 Days After', 'USER', 'MEDIUM', NULL, NULL, ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '8e4d48d9-4e9c-51f2-b4e5-e39ec4dabbb6', 3, 'Nutrition', NULL, 'SMALL_RUMINANT', NULL, 'User Action',
  NULL, 'Update Feed', NULL, 'تحديث العلف',
  'The breeding stage has changed so please update the feed', 'مرحلة التزاوج قد تغيرت، الرجاء تحديث العلف', 'GroupName (group animal is in )', 'Change in Breeding', 'If move to Ready for breeding for goats/Sheep ask if using sponges, and mark for de-worming',
  'Next Day', 'USER', 'MEDIUM', NULL, NULL, ARRAY['IN_APP'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '9ccd9598-0998-500a-a773-c906a1b1609c', 4, 'Nutrition', NULL, 'ALL', NULL, 'User Action',
  NULL, 'Update Feed', NULL, 'تحديث العلف',
  'The lacation cycle has changed so please update the feed', 'دورة الحليب قد تغيرت، الرجاء تحديث العلف', 'GroupName (group animal is in )', 'Change in Lactation', NULL,
  'Next Day', 'USER', 'MEDIUM', NULL, NULL, ARRAY['IN_APP'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  'e50146cb-bd79-5455-af12-2df7f072f2fe', 5, 'Nutrition', NULL, 'ALL', NULL, 'User Action',
  'Please update feed quantities for {Group Name}', 'Update Feed for {Group Name}', 'الرجاء تحديث كميات العلف لاسم المجموعة {اسم المجموعة}', 'تحديث العلف لاسم المجموعة {اسم المجموعة}',
  'The group size has changed so please update the feed', 'لقد تغيّر عدد أفراد المجموعة، الرجاء تحديث كميات العلف', 'GroupName', 'Group Size Changed', NULL,
  'Next Day', 'USER', 'MEDIUM', NULL, NULL, ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '664527e3-37b7-5b76-a7cd-1e58414dfb58', 9, 'Inventory', NULL, NULL, 'Inventory Low', 'Inventory night Job',
  'Reminder: {Product Name} is running low', 'Buy more {Product Name}', 'تذكير: الكمية المتبقية من {اسم المنتج} منخفضة', 'شراء المزيد من {اسم المنتج}',
  'Based on current usage you have 2 weeks of  {Product Name} left. Please purchase more or an alternative, as inventory levels are low', 'وفقًا لمعدل الاستخدام الحالي، يتبقى لديك أسبوعان من {اسم المنتج}. الرجاء شراء كمية إضافية أو اختيار بديل، حيث إن مستوى المخزون منخفض.', 'General', 'Low Inventory', NULL,
  'Next Day', 'SYSTEM', 'HIGH', NULL, NULL, ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '8722740f-1687-5720-b374-111eb9fc110a', 10, 'Breeding', NULL, 'CATTLE', 'Cow is a Heifer', 'Cattle Breeding Night Job',
  'Check {Tag Number} for first heat', 'Check for First Heat {Tag Number}', NULL, NULL,
  'Based on the current age the Heifer is due her first Heat Detection, please record', NULL, 'TagNumber', NULL, 'Is heifer over 12 months old',
  'Next Day', 'SYSTEM', 'HIGH', 'Daily', NULL, ARRAY['IN_APP'],
  FALSE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '8c270745-0538-5e09-a316-210952076d19', 11, 'Breeding', NULL, 'CATTLE', 'Cow is a Heifer', 'Cattle Breeding Night Job',
  'Check {Tag Number} for second heat for first insemmination', 'Check for Second Heat {Tag Number} to start insemmination.', NULL, NULL,
  'Close this task only after you have
Requested for AI insemination between  10-14 hours after  Heat detected.
Asked AI person to do uterus health assessment, if issues make medical note.
Then recorded the AI process, Sire, Sire Breed, Administered By , Date , picture of the straw.', NULL, 'TagNumber', NULL, 'Is heifer over 12 months old',
  '18Days After the First Heat Detected', 'SYSTEM', 'HIGH', NULL, 'When First Heat Detected - Creates  Second Heat Detection Task', ARRAY['IN_APP', 'PUSH'],
  FALSE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '6371524f-ac24-55a7-bc19-b4e7bcdaedc0', 12, 'Breeding', NULL, 'ALL', 'Cow is a Heifer', 'Cattle Breeding Night Job',
  'Please preliminary Book AI for {Tag Number}', 'Book AI for {Tag Number}', NULL, NULL,
  'Based on the heat cycle notify the AI person that you will potentially need his time 18-21 Days time', NULL, 'TagNumber', NULL, 'Is heifer over 12 months old',
  '18Days After the First Heat Detected', 'SYSTEM', 'HIGH', 'Daily', NULL, ARRAY['IN_APP'],
  FALSE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  'dd77cc1e-8346-5ed0-8a9c-8062ff268e49', 13, 'Breeding', NULL, 'ALL', 'Cow with a previous Birth', 'Cattle Breeding Night Job',
  'Please preliminary Book AI for {Tag Number}', 'Book AI for {Tag Number} and check for heat.', NULL, NULL,
  'Based on the last birth  notify the AI person that you will potentially need his time 18-21 Days time', NULL, 'TagNumber', NULL, 'Had a birth 20 Days previous',
  '40Days After the Birth', 'SYSTEM', 'HIGH', 'Daily', '40Days After the Birth', ARRAY['IN_APP'],
  FALSE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  'f4de807c-ac3b-5d7c-bae9-689e907e81bf', 14, 'Breeding', NULL, 'ALL', 'Cow with a previous Birth', 'Cattle Breeding Night Job',
  'Check {Tag Number} for  heat for first insemmination', 'Check {Tag Number} heat to commence insemmination.', NULL, NULL,
  'Close this task only after you have
Requested for AI insemination between  10-14 hours after  Heat detected.
Asked AI person to do uterus health assessment, if issues make medical note.
Then recorded the AI process, Sire, Sire Breed, Administered By , Date , picture of the straw.', NULL, 'TagNumber', NULL, 'Had a birth 40 Days previous',
  '40Days After the Birth', 'SYSTEM', 'HIGH', NULL, NULL, ARRAY['IN_APP', 'PUSH'],
  FALSE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  'ef53bf17-2713-5b01-ac4c-3c5980509341', 15, 'Breeding', NULL, 'CATTLE', 'Cow has had first Insemmination', 'Cattle Breeding Night Job',
  'Book pregnancy check', 'Book Pregnancy check for {TagNumbers,}', NULL, NULL,
  'Book Pregnancy check for {TagNumbers,}', NULL, 'TagNumber', NULL, 'Has been insemminated 30 Days ago',
  '35 Days After Insemmination', NULL, 'HIGH', NULL, 'Insemmination recorded', ARRAY['IN_APP', 'PUSH'],
  FALSE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '9f8b7833-6397-5876-b977-f63cd02c8008', 16, 'Breeding', NULL, 'CATTLE', 'Cow has first  Insemmination and not pregnant', 'Cattle Breeding Night Job',
  'Check {Tag Number} for  heat for 2nd insemmination', 'Check {Tag Number} for  heat for 2nd insemmination', NULL, NULL,
  'Close this task only after you have
Notified AI person you will need services withing 2-7 Days
Requested for AI insemination between  10-14 hours after  Heat detected.
Asked AI person to do uterus health assessment, if issues make medical note.
Then recorded the AI process, Sire, Sire Breed, Administered By , Date , picture of the straw.', NULL, 'TagNumber', NULL, 'Has had first insemmination 36 Days ago and not marked pregnant',
  '36 Days After Insemmination', 'SYSTEM', 'HIGH', NULL, 'Insemmination recorded', ARRAY['IN_APP', 'PUSH'],
  FALSE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  'fe715ff6-af54-523d-937a-7ff4e734b6a3', 17, 'Breeding', NULL, 'CATTLE', 'Cow has had 2nd  Insemmination and not pregnant', 'Cattle Breeding Night Job',
  'Check {Tag Number} for  heat for 3rd  insemmination', 'Check {Tag Number} for  heat for 3rd insemmination', NULL, NULL,
  'Recommendation: Change AI person 
Close this task only after you have
Notified the new AI person you will need services withing 2-7 Days
Requested for AI insemination between  10-14 hours after  Heat detected.
Asked new AI person to do uterus health assessment, if issues make medical note.
Then recorded the AI process, Sire, Sire Breed, Administered By , Date , picture of the straw.', NULL, 'TagNumber', NULL, 'Has had second insemmination 36 Days ago and not marked pregnant',
  '36 Days After 2nd Insemmination', 'SYSTEM', 'HIGH', NULL, 'Insemmination recorded', ARRAY['IN_APP', 'PUSH'],
  FALSE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  'd83291a9-07f2-5c32-ba61-90dc2a2a5a68', 18, 'Breeding', NULL, 'CATTLE', 'Cow has had 3rd  Insemmination and not pregnant', 'Cattle Breeding Night Job',
  'Call vet to check  {Tag Number} for health issues', 'Call vet to check  {Tag Number} for health issues as not getting pregnant', NULL, NULL,
  'Recommended Action; Call vet and decide if to cull the animal or use a Bull', NULL, 'TagNumber', NULL, 'Has had thirs insemmination 36 Days ago and not marked pregnant',
  '36 Days After 3rd Insemmination', 'SYSTEM', 'HIGH', NULL, 'Insemmination recorded', ARRAY['IN_APP', 'PUSH'],
  FALSE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '2b947e88-cf61-5308-9f14-2039745171b6', 19, 'Breeding', NULL, 'ALL', 'Pregnanices Due', 'Breeding Night Job',
  NULL, 'Pregnancies Due', NULL, 'مواعيد الولادة المتوقعة',
  'There are ?? Animals due this week', 'يوجد ?? حيوان من المتوقع ولادته هذا الأسبوع', 'General', NULL, '7 Days before',
  NULL, 'SYSTEM', 'MEDIUM', 'Weekly', NULL, ARRAY['IN_APP'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '3a4a475f-5095-58ad-bfc9-dcfb3166e569', 20, 'Breeding', NULL, 'ALL', 'Pregnancy Overdue', 'Breeding Night Job',
  NULL, '"Tag Number" is overdue', NULL, '(Tتجاوز موعده Tag number',
  '"Tag Number" maybe over due on pregnancy please check', 'يرجى التحقق من Tag Number فقد يكون قد تجاوز موعد الولادة', 'TagNumber', NULL, '1 Day After',
  NULL, 'SYSTEM', 'HIGH', NULL, NULL, ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '6e4c35fc-0f68-57fb-ba9a-33a0ca96ad65', 21, 'Breeding', NULL, NULL, NULL, NULL,
  NULL, 'Check for Breeding', NULL, 'تحقّق من التلقيح',
  'Please check females (list based on criteria)  for Breeding and mark ready to breed to start updating updating nutrition and do de-worming', 'يرجى التحقق من الإناث (وفقًا للمعايير) للتلقيح، وعلّمها بأنها جاهزة للتلقيح لتحديث التغذية والقيام بعملية إزالة الديدان', 'General', '8 weeks after last lambing or 6 months old', NULL,
  NULL, 'SYSTEM', 'HIGH', NULL, NULL, ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '7af2e4b5-fbad-5c53-85f9-d61240dd97ad', 24, 'Breeding', NULL, 'SMALL_RUMINANT', 'Ready to Breed Using Sponges', 'Database',
  NULL, 'Insert Sponges', NULL, 'إدخال الإسفنجات',
  'Please insert Sponges in Females to prepare for insemmination', 'الرجاء إدخال الإسفنجات في الإناث للتحضير للتلقيح.', 'GroupName', '2 weeks after ready to breed and sponge ticked', 'Should be done 2 weeks before',
  NULL, 'USER', 'HIGH', NULL, 'When Acknowledge - Creates next Task', ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, 'Potentially Notify in future'
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '0e3aa227-aec4-537f-a516-0cb83321b36d', 25, 'Breeding', NULL, 'SMALL_RUMINANT', 'Ready to Breed and not Using Using Sponges', 'Database',
  NULL, 'Introduce male to the Group', NULL, 'إدخال الذكر إلى المجموعة',
  'Please introduce a male to the group not more than 25 females. if using more than one please use marker to know the successful sire', 'الرجاء إدخال ذكر إلى المجموعة، على ألا يتجاوز العدد 25 أنثى لكل ذكر. إذا تم استخدام أكثر من ذكر، يُفضل استخدام علامة لتحديد الأب الناجح.', 'GroupName', 'Ready to Breed for 2 weeks', NULL,
  NULL, 'USER', 'HIGH', NULL, 'When Acknowledge - Creates next Task', ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '7d49c290-5624-5768-84be-ce4fa7e20a3a', 26, 'Breeding', NULL, 'SMALL_RUMINANT', 'Sponges Inserted', NULL,
  NULL, 'Remove Sponges', NULL, 'إزالة الإسفنجات',
  'Plerase remove sponges and wait 11 days fand 14 days fro sheep
For Goats  inject with PMSG and PGF to Alpha, and meat withdrawal is 2 days

For Sheep Inject with PMSG  and meat withdrawal is 2 days', 'الرجاء إزالة الإسفنجات والانتظار من 11 إلى 14 يومًا في حالة النعاج.

في حالة الماعز، يتم الحقن بهرموني PMSG وPGF إلى ألفا، وفترة سحب اللحوم هي يومان.

في حالة النعاج، يتم الحقن بهرمون PMSG، وفترة سحب اللحوم هي يومان.', 'GroupName', '2 weeks after sponge insertion task acknowledged', NULL,
  NULL, 'USER', 'HIGH', NULL, 'Add PMSG and (PGF to Alpha) as vaccination event', ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '606d8329-0f34-56b3-917f-e588a2c10e1b', 27, 'Breeding', NULL, 'SMALL_RUMINANT', 'Sponges Removed', 'Database',
  NULL, 'Introduce male to the Group', NULL, 'إدخال الذكر إلى المجموعة',
  'Please introduce a male to the group not more than 25 females. if using more than one please use marker to know the successful sire', 'الرجاء إدخال ذكر إلى المجموعة، على ألا يتجاوز العدد 25 أنثى لكل ذكر. إذا تم استخدام أكثر من ذكر، يُفضل استخدام علامة لتحديد الأب الناجح.', 'GroupName', '24 hours after Spnges removes task acknoledged', NULL,
  NULL, 'USER', 'HIGH', NULL, 'When Acknowledge - Creates next Task', ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '90705797-d476-5ec0-b4d9-25d2554ad411', 28, 'Medical', NULL, NULL, NULL, NULL,
  NULL, 'De-worm immediately', NULL, 'إجراء عملية إزالة الديدان فورًا',
  'Please de-worm your females immediately before they get pregnant', 'الرجاء إعطاء الإناث مضاد الديدان فورًا قبل حدوث الحمل', 'GroupName', 'Moved to Ready to Breed', 'If animals in group not de-wormed and are one in as Ready to Breed',
  NULL, 'USER', 'HIGH', NULL, NULL, ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '686bb6c5-c54f-5233-a6ac-6e05b36700af', 29, 'Breeding', NULL, 'SMALL_RUMINANT', 'Male Introduced', 'Database',
  NULL, 'Remove  male from the Group', NULL, 'إزالة الذكر من المجموعة',
  'Please remove the males from the group', 'الرجاء إخراج الذكور من المجموعة.', 'GroupName', '7 days after male with group', NULL,
  NULL, 'USER', 'MEDIUM', NULL, 'When Acknowledge - Creates next Task', ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  'e77cdcbe-7c7d-51ee-b189-5f1188d56a95', 30, 'Breeding', NULL, 'SMALL_RUMINANT', 'Male removed', 'Database',
  NULL, 'Pregnancy Check', NULL, 'فحص الحمل',
  'Please do pregancy check no to determine pregnancy , due dates and twinning rates to ensure proper nutrition. Record the sire for  the conception.', 'الرجاء إجراء فحص حمل الآن لتحديد حالة الحمل، مواعيد الولادة، وعدد الأجنة لضمان التغذية المناسبة. يُرجى تسجيل الذكر المسؤول عن التلقيح.', 'GroupName', '5 weeks after male removed acknowledged', NULL,
  NULL, 'USER', 'HIGH', NULL, 'When Acknowledge - Creates next Task', ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  'a4aa1c39-9521-5c1e-9ebe-dd4f9f2ddd35', 31, 'Breeding', NULL, 'CATTLE', 'Cow is 20 Days post calving', NULL,
  '{Tag Number} is now ready to Breed', '{Tag Number} is now ready to Breed', NULL, NULL,
  NULL, NULL, 'TagNumber', NULL, '20 Days after calving',
  NULL, 'SYSTEM', 'MEDIUM', NULL, NULL, ARRAY['IN_APP'],
  FALSE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  'ffea930a-c230-57ec-a18f-26f343c54835', 32, 'Breeding', NULL, 'SMALL_RUMINANT', 'Pregnant', 'Database',
  NULL, 'Check "Tag Number" for Lambing', NULL, 'تحقق من Tag Number للولادة',
  'A doe within 12 - 16 hours of kidding will wiggle its tail several times. During this time, the doe will often start "baby talking" and dig and stir the bedding in her pen or isolate herself from the herd. It will be uneasy and may lie down and get up frequently.
Then move to a Maternity Pen', '‏تقوم العنزة خلال 12 إلى 16 ساعة قبل الولادة بهز ذيلها عدة مرات. وخلال هذه الفترة، تبدأ غالبًا بإصدار أصوات مميزة ("تتحدث مع صغيرها")، وتقوم بالحفر وتحريك الفرشة في مكانها أو تعزل نفسها عن القطيع. تظهر عليها علامات القلق وقد تستلقي وتنهض بشكل متكرر.
بعدها يجب نقلها إلى حظيرة الولادة.', 'TagNumber', '1 week before the estmimated due Date', NULL,
  NULL, 'SYSTEM', 'HIGH', NULL, NULL, ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  'be2a3e1d-97a3-5282-88d3-e8961f02c080', 33, 'Breeding', NULL, 'CATTLE', 'Given Birth', 'Database',
  NULL, 'Ready to Breed - Check for Heat', NULL, 'جاهزة للتلقيح – تحقق من دورة الشبق',
  'The cow is not 45 Days since given birth and we should start preparing  her for breeding , please check for signs of heat.', 'البقرة لم يمر عليها 45 يومًا منذ الولادة، ويجب أن نبدأ بتحضيرها للتلقيح. يُرجى مراقبتها بحثًا عن علامات الشبق.', 'TagNumber', '45 Days after Birth', NULL,
  NULL, 'SYSTEM', 'HIGH', NULL, NULL, ARRAY['IN_APP'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '7aa60ee6-e1ba-5027-988f-34223ae44411', 35, 'Medical', NULL, 'SMALL_RUMINANT', 'Pregnant', 'Database',
  NULL, 'Watch for Birth', NULL, 'راقب الولادة',
  'When animal is born 
CREATE EMERGENCY PROCEDURE FOR LAMB NOT BREATHING/FEEDING
Wash udder and hind parts of the doe at the end of kidding.
Break umbilical cord if necessary
dip the navel in a 7% tincture of iodine
spray the hooves with a 7% tincture of iodine
Open the does teat

Weigh newborn lamb
Apply temporary tag
Create animal record(s)
Tie the umbilical cord
Check if lamb is able to stand and suckle within first 15 min', 'عند ولادة الحيوان:

إنشاء إجراء طارئ لحالات عدم تنفس/رضاعة الخروف حديث الولادة
غسل الضرع والأجزاء الخلفية للأم بعد انتهاء الولادة
قطع الحبل السري إذا لزم الأمر
غمس السرة في صبغة يود 7%
رش الحوافر بصبغة يود 7%
فتح ضرع الأم والتأكد من خروج الحليب

وزن الخروف حديث الولادة
وضع بطاقة تعريف مؤقتة
إنشاء سجل للحيوان
ربط الحبل السري
التأكد من قدرة الخروف على الوقوف والرضاعة خلال أول 15 دقيقة', 'TagNumber', '2 Days before Due Date', NULL,
  NULL, 'SYSTEM', 'HIGH', NULL, NULL, ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '9db9cd45-ed7e-5c33-92d5-c31b1f50918f', 36, 'Medical', NULL, 'CATTLE', 'Pregnant', NULL,
  NULL, 'Watch For Birth', NULL, 'راقب الولادة',
  'When animal is born 
CREATE EMERGENCY PROCEDURE FOR Calf NOT BREATHING/FEEDING 
When Born tiew umbilical cord', 'عند ولادة الحيوان:

إنشاء إجراء طارئ في حال كان العجل لا يتنفس أو لا يرضع

عند الولادة، يتم ربط الحبل السري', 'TagNumber', '3 Days before Due Date', NULL,
  NULL, NULL, NULL, NULL, NULL, ARRAY[]::TEXT[],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  'ea8b4a41-a970-5c9f-b9d3-eab48820f5a8', 37, 'Medical', NULL, NULL, NULL, NULL,
  NULL, '"Tag Number" has had miscarraige', NULL, '"""""" قد أجهضت',
  '"Tag Number" has miscarriage and will need Womb cleaned,  take Temperature, if Temperature "High" call vet', '"""""  تعرّض للإجهاض ويحتاج إلى تنظيف الرحم، يرجى قياس الحرارة، وإذا كانت مرتفعة، اتصل بالطبيب البيطري.', 'TagNumber', 'Miscarriage', NULL,
  NULL, 'USER', NULL, NULL, 'Enters record into Medical Reocrd to clean Womb and take Temperature, if Temperature High call vet', ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  'e6f6c209-06f9-5280-8089-5182c6f1ac16', 45, 'Weather', NULL, NULL, NULL, NULL,
  'Weather Alert: Severe weather fluctuations', 'Monitor livestock closely', NULL, 'تقلبات جوية حادة',
  'Significant temperature fluctuations expected. Monitor livestock closely for signs of stress or illness, and adjust feed and shelter arrangements accordingly.', 'توقع تقلبات كبيرة في درجات الحرارة
راقب الماشية عن كثب بحثًا عن علامات التوتر أو المرض، وقم بتعديل الترتيبات المتعلقة بالتغذية والمأوى حسب الحاجة.', 'General', 'Temperature fluctuations of more than 15°C within a 24-hour period.', NULL,
  'Next Day', NULL, NULL, NULL, NULL, ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  'c2f3d6c2-51da-59a8-bd95-75ad503d93b4', 46, 'Weather', NULL, NULL, NULL, NULL,
  'Weather Alert: Temperature below -5C', 'Ensure livestock ready for cold', NULL, 'درجة حرارة أقل من -٥ مئوية',
  'Temperatures are dropping below -5°C. Provide additional bedding and shelter to protect livestock from the cold. Increase energy feed to help animals maintain body heat.', 'درجات الحرارة تنخفض إلى ما دون -٥ مئوية
قدّم فرشًا إضافيًا ومأوى لحماية الماشية من البرد. زد من تغذية الطاقة لمساعدتها على الحفاظ على حرارة الجسم.', 'General', 'Tomorrow min temp <-5C', NULL,
  'Next Day', NULL, NULL, NULL, NULL, ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  'b9c7dd61-44de-57e0-9ab5-806028cd5bec', 47, 'Weather', NULL, NULL, NULL, NULL,
  'Weather Alert: Temperature above 40C', 'Ensure livestock are in shade', NULL, 'درجة حرارة أعلى من ٤٠ مئوية',
  'Temperatures are exceeding 40°C. Ensure all livestock have access to shaded areas and fresh, clean water. Adjust feeding times to early morning or late evening to reduce heat stress.', 'درجات الحرارة تتجاوز ٤٠ مئوية
تأكد من وجود مناطق مظللة ومياه نظيفة وعذبة لجميع الماشية. غيّر مواعيد التغذية إلى الصباح الباكر أو المساء المتأخر لتقليل الضغط الحراري.', 'General', 'Tomorrow max temp >40C', NULL,
  'Next Day', NULL, NULL, NULL, NULL, ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '3c48bab5-bb9b-54bd-b325-de02d1ac9b88', 48, 'Weather', NULL, NULL, NULL, NULL,
  'Weather Alert: Heavy wind', 'Monitor livestock closely', NULL, 'رياح قوية',
  'Winds exceeding 40 km/h forecasted. Secure loose objects and ensure livestock are kept in wind-protected shelters to avoid stress and injury.', 'رياح تتجاوز سرعتها ٤٠ كم/س متوقعة
قم بتأمين الأجسام غير المثبتة وتأكد من وجود الماشية في ملاجئ محمية من الرياح لتجنب التوتر والإصابات.', 'General', 'Sustained winds above 40 km/h or gusts exceeding 60 km/h.', NULL,
  'Next Day', NULL, NULL, NULL, NULL, ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '891f720c-c7fc-5914-bc94-5a063420b18d', 49, 'Weather', NULL, NULL, NULL, NULL,
  'Weather Alert: Heavy rain', 'Monitor livestock closely', NULL, 'أمطار غزيرة',
  'Heavy rainfall expected. Move livestock to elevated, sheltered areas to prevent flooding. Check for signs of hoof damage and provide dry bedding where possible.', 'توقع أمطار غزيرة
انقل الماشية إلى مناطق مرتفعة ومحمية لتجنب الفيضانات. راقب علامات تلف الحوافر وقدّم فراشًا جافًا إن أمكن.', 'General', 'Rainfall exceeding 50 mm in 24 hours or continuous rain over 3 days with totals exceeding 100 mm.', NULL,
  'Next Day', NULL, NULL, NULL, NULL, ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '2c7f4f45-2539-5fe5-a389-5b25de7762e4', 50, 'Weather', NULL, NULL, NULL, NULL,
  'Weather Alert: Snow', 'Monitor livestock closely', NULL, 'ثلوج',
  'Snow/ice conditions detected. Clear access to feed and water, provide high-energy feed, and monitor livestock closely for signs of frostbite or injuries.', 'اكتشاف ظروف ثلجية أو جليدية
افتح الطرق المؤدية إلى العلف والماء، وقدّم علفًا غنيًا بالطاقة، وراقب الماشية جيدًا لرصد علامات التجمّد أو الإصابة.', 'General', 'Snow accumulation exceeding 10 cm in 24 hours or freezing rain leading to icy conditions.', NULL,
  'Next Day', NULL, NULL, NULL, NULL, ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '4134111b-16d7-5bbf-92df-e11d5917e901', 51, 'Weather', NULL, NULL, NULL, NULL,
  'Weather Alert: Sandstorm', 'Monitor livestock closely', NULL, 'عاصفة رملية',
  'Dust storm warning issued. Move livestock to enclosed shelters to protect them from respiratory stress and eye irritation. Provide dust-free water and feed', 'تحذير من عاصفة رملية
انقل الماشية إلى ملاجئ مغلقة لحمايتها من التوتر التنفسي وتهيج العيون. قدّم مياه وعلفًا خاليين من الغبار.', 'General', 'Winds carrying particulate matter reducing visibility below 1 km.', NULL,
  'Next Day', NULL, NULL, NULL, NULL, ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '5c28483f-489b-57fe-8c85-b51cc9e07e1f', 52, 'Weather', NULL, NULL, NULL, NULL,
  'Weather Alert: Thunderstorm', 'Monitor livestock closely', NULL, 'عاصفة رعدية',
  'Thunderstorms with lightning and hail expected. Move livestock to enclosed shelters and minimize their exposure to open areas to reduce injury risk', 'توقع عواصف رعدية مع برق وبَرَد
انقل الماشية إلى ملاجئ مغلقة وقلّل من تعرضها للمناطق المفتوحة لتقليل خطر الإصابة.', 'General', 'Severe weather warnings for lightning strikes, hail, and strong gusts above 70 km/h.', NULL,
  'Next Day', NULL, NULL, NULL, NULL, ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '80c26fe0-e1d3-5968-bb92-ba3d5808994b', 53, 'Weather', NULL, NULL, NULL, NULL,
  'Weather Alert: Frost', 'Monitor livestock closely', NULL, 'صقيع',
  'Frost conditions detected overnight. Move grazing animals to areas with forage access and consider additional feed to compensate for frost-damaged grass.', 'رصد حالات صقيع ليلي
انقل الحيوانات التي ترعى إلى مناطق يتوفر فيها العلف، وفكر في توفير تغذية إضافية لتعويض العشب المتضرر من الصقيع.', 'General', 'Overnight temperatures below 0°C, especially in combination with dew or precipitation.', NULL,
  'Next Day', NULL, NULL, NULL, NULL, ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '1752a04c-7bfb-5962-83ab-00182ca06087', 57, 'Medical', NULL, NULL, NULL, NULL,
  'Reminder: Animal {Tag Number} is ill', 'Treat {Tag Number}', NULL, 'الوسم "123" مريض',
  'Please continue the treament of {Tag Number} and update the Treatment Notes', NULL, 'TagNumber', 'Animal marked Ill', NULL,
  'Every Day Animal is ill', 'USER', 'HIGH', NULL, NULL, ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '2e8abb69-5d93-55c6-b999-77727f0497b4', 58, 'Medical', NULL, NULL, NULL, NULL,
  NULL, '"Vaccination Due"', NULL, NULL,
  NULL, NULL, NULL, NULL, 'if Vaccination due and vaccination over 12 months since previous',
  NULL, 'SYSTEM', NULL, NULL, NULL, ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, '§'
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '0cb628e2-6eca-588d-b99e-f405392bc418', 59, 'Medical', NULL, NULL, NULL, NULL,
  NULL, 'Booster Due', NULL, NULL,
  NULL, NULL, NULL, NULL, NULL,
  NULL, 'SYSTEM', 'HIGH', NULL, NULL, ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  'e450f0d8-e0d9-5f2b-ba28-5c3a08ad888e', 60, 'Medical', NULL, NULL, NULL, NULL,
  NULL, 'Milk Withdrawal', NULL, NULL,
  '?? Number of animals in Milk Withdrawal', NULL, NULL, NULL, NULL,
  NULL, 'SYSTEM', 'MEDIUM', NULL, NULL, ARRAY['IN_APP'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '81424094-bf4c-5e00-9c94-8789e2c9ab27', 61, 'Medical', NULL, NULL, NULL, NULL,
  NULL, 'Meat With drawal', NULL, NULL,
  '?? Number of animals in Meat Withdrawal', NULL, NULL, NULL, NULL,
  NULL, 'SYSTEM', 'MEDIUM', NULL, NULL, ARRAY['IN_APP'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '5c1d06f6-4d9f-5b12-87ad-ec91db6b6a7f', 62, 'Medical', NULL, NULL, NULL, NULL,
  NULL, 'Animals Ill', NULL, NULL,
  NULL, NULL, NULL, NULL, NULL,
  NULL, NULL, NULL, NULL, NULL, ARRAY[]::TEXT[],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '31278fe4-a5e7-5332-a86c-26896b7c947a', 63, 'Medical', NULL, NULL, NULL, NULL,
  'Reminder: Health Check Due', 'Female Health Check', NULL, 'فحص صحي للإناث',
  'Check for Internal and external parasites. Deworm as needed and check feet', 'تحقّق من الطفيليات الداخلية والخارجية، وقم بإعطاء الدواء الطارد للديدان إذا لزم الأمر، وفحص الأقدام.', 'General', '10 weeks after set as Ready to Breed', NULL,
  '10 weeks after set as Ready to Breed', 'SYSTEM', 'MEDIUM', NULL, NULL, ARRAY['IN_APP'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '9ec98f73-f59b-5b84-a82c-1e839f26a67d', 64, 'Medical', NULL, NULL, NULL, NULL,
  'Reminder: Health Check Due', 'Female Health Check', NULL, 'فحص صحي للإناث',
  'Check for Internal and external parasites. Deworm as needed and check feet', 'تحقّق من الطفيليات الداخلية والخارجية، وقم بإعطاء الدواء الطارد للديدان إذا لزم الأمر، وفحص الأقدام.', 'General', '14 weeks after set as Ready to Breed', NULL,
  '14 weeks after set as Ready to Breed', 'SYSTEM', 'MEDIUM', NULL, NULL, ARRAY['IN_APP'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '2f93d592-319a-5976-ad14-b60c576a23d3', 65, 'Medical', NULL, NULL, NULL, NULL,
  'Reminder: Health Check Due', 'Female Health Check', NULL, 'فحص صحي للإناث',
  'Check for Internal and external parasites. Deworm as needed and check feet', 'تحقّق من الطفيليات الداخلية والخارجية، وقم بإعطاء الدواء الطارد للديدان إذا لزم الأمر، وفحص الأقدام.', 'General', '18 weeks after set as Ready to Breed', NULL,
  '18 weeks after set as Ready to Breed', 'SYSTEM', 'MEDIUM', NULL, NULL, ARRAY['IN_APP'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '995a4f4a-07d7-52ec-85b1-05ac59e44ed1', 68, 'Vaccinations', NULL, 'ALL', 'Vaccine not registered', 'Database',
  NULL, 'Clostridium Vaccination Due', NULL, 'اللقاح ضد الكلوستريديوم مستحق الآن',
  'Newborn animals should be vaccinated on their eighth week of age then they will be revaccinated after 6-4 weeks
·         Mothers should be vaccinated during their second semester of pregnancy, and then they will be revaccinated after 6-4 weeks (provided that the second vaccination should be twoweeks before delivery)
·         Animals or babies that are first time to be vaccinated should be revaccinated after 6-4 weeks
·         Babies of the unvaccinated mothers should be vaccinated after delivery then they will be revaccinated after 6-4 weeks', 'يجب تلقيح الحيوانات حديثة الولادة في الأسبوع الثامن من عمرها، ثم يُعاد تلقيحها بعد 4 إلى 6 أسابيع.

يجب تلقيح الأمهات خلال الثلث الثاني من الحمل، ثم يُعاد تلقيحهن بعد 4 إلى 6 أسابيع، بشرط أن يتم التلقيح الثاني قبل الولادة بأسبوعين.

الحيوانات أو الصغار الذين يتم تلقيحهم لأول مرة يجب أن يُعاد تلقيحهم بعد 4 إلى 6 أسابيع.

صغار الأمهات غير الملقحات يجب أن يُلقحوا بعد الولادة مباشرة، ثم يُعاد تلقيحهم بعد 4 إلى 6 أسابيع.', NULL, 'Send march/April & Sept/October', 'Send if no vaccination recorded during the time period',
  NULL, 'SYSTEM', 'HIGH', 'Weekly', NULL, ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, 'Start with basic, Later workout which animals should be vaccinated'
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '55821824-fddb-5794-8192-3078b636bbe1', 69, 'Vaccinations', NULL, 'ALL', 'Vaccine not registered', 'Database',
  NULL, 'Pasteurellosis', NULL, 'التسمم الدموي',
  'Newborn animals should be vaccinated on the eight weeks of age then they will be revaccinated after 6-4 weeks
Mothers should be vaccinated during their second semester of pregnancy, and then they will be revaccinated after 6-4 weeks (provided that the second vaccination should be twoweeks before delivery)
Animals or babies that are first time to be vaccinated should be revaccinated after 3 weeks', 'يجب تلقيح الحيوانات حديثة الولادة عند عمر 8 أسابيع، ثم إعادة التلقيح بعد 4 إلى 6 أسابيع.
يجب تلقيح الأمهات في الثلث الثاني من الحمل، ثم إعادة التلقيح بعد 4 إلى 6 أسابيع، بشرط أن يتم التلقيح الثاني قبل الولادة بأسبوعين على الأقل.
الحيوانات أو الصغار التي يتم تلقيحها لأول مرة يجب إعادة تلقيحها بعد 3 أسابيع.', NULL, 'Send march/April & Sept/October', 'Send if no vaccination recorded during the time period',
  NULL, 'SYSTEM', 'HIGH', 'Weekly', NULL, ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, 'Start with basic, Later workout which animals should be vaccinated'
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  'ad81a5b9-c545-5b77-852a-67fd740e0e4e', 70, 'Vaccinations', NULL, 'ALL', 'Vaccine not registered', 'Database',
  NULL, 'Smallpox', NULL, 'الجدري',
  NULL, NULL, NULL, 'October,Novemeber, December', 'Send if no vaccination recorded during the time period',
  NULL, 'SYSTEM', 'HIGH', 'Weekly', NULL, ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '32016afa-2ffe-5a3f-912c-c16f560ac8cf', 71, 'Vaccinations', NULL, 'ALL', 'Vaccine not registered', 'Database',
  NULL, 'Plague of small ruminants', NULL, 'طاعون المجترات الصغيرة',
  'Newborn animals should be vaccinated when they reach three
months of age
Pregnant mothers should not be vaccinated during their final stage of pregnancy (especially last two weeks
of pregnancy)', 'يجب تلقيح الحيوانات حديثة الولادة عند بلوغها عمر ثلاثة أشهر.
يُمنع تلقيح الأمهات الحوامل خلال المرحلة الأخيرة من الحمل (خصوصًا آخر أسبوعين قبل الولادة).', NULL, 'October,Novemeber, December', 'Send if no vaccination recorded during the time period',
  NULL, 'SYSTEM', 'HIGH', 'Weekly', NULL, ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  'd295622a-3e88-505b-a06a-51b9850d54e1', 72, 'General', NULL, 'GOAT', NULL, NULL,
  NULL, 'Infectious Crystalline Pneumonia', NULL, 'الالتهاب الرئوي البلوري المعدي',
  'Vaccinations should be given to animals that are more than 6 months of age', 'يجب إعطاء اللقاحات للحيوانات التي يزيد عمرها عن 6 أشهر.', NULL, 'Mar,Apr, May, Sept,Oct,Nove', 'Send if no vaccination recorded during the time period',
  NULL, 'SYSTEM', 'HIGH', 'Weekly', NULL, ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '8f61b219-fb0a-5371-830f-f7958d09088a', 73, 'General', NULL, NULL, NULL, NULL,
  NULL, 'Foot and Mouth', NULL, 'الحمى القلاعية',
  'Newborn animals should be vaccinated when they reach three
months of age then they will be revaccinated after 3 weeks
Pregnant mothers should not be vaccinated during their third
trimester of pregnancy
Animals or babies that are first time to be vaccinated should be revaccinated after 3 weeks', 'يجب تطعيم الحيوانات حديثة الولادة عندما تبلغ عمر ثلاثة أشهر، ثم يُعاد تطعيمها بعد 3 أسابيع.
يُمنع تطعيم الأمهات الحوامل خلال الثلث الأخير من الحمل.
الحيوانات أو الصغار الذين يتلقون التطعيم لأول مرة يجب إعادة تطعيمهم بعد 3 أسابيع.', NULL, 'Feb,Mar,April, August,Sept', 'Newborn animals should be vaccinated when they reach three
months of age then they will be revaccinated after 3 weeks
Pregnant mothers should not be vaccinated during their third
trimester of pregnancy
Animals or babies that are first time to be vaccinated should be revaccinated after 3 weeks',
  NULL, 'SYSTEM', 'HIGH', 'Weekly', NULL, ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '5808f06f-8ac3-5c3b-baa9-894ec91944e9', 88, 'Milk', NULL, 'CATTLE', 'Pregnant', NULL,
  NULL, 'Move Lactation to Dry-Off', NULL, 'نقل دورة الحليب إلى مرحلة الجفاف',
  'In order to prepare the animal for a healthy birth and provide better nutrition please move to Dry-Off', 'لتحضير الحيوان لولادة صحية وتوفير تغذية أفضل، الرجاء نقلها إلى مرحلة الجفاف.', 'TagNumber', 'Pregnant', '2 months before Due Date',
  NULL, 'SYSTEM', 'HIGH', NULL, NULL, ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  'ce69319b-21fc-5065-819c-f57d59a6ccfc', 89, 'Milk', NULL, 'CATTLE', 'Pregnant', NULL,
  NULL, 'Move Lactation to Close', NULL, 'نقل دورة الحليب إلى الإغلاق',
  'In order to prepare the animal for a healthy birth and provide better nutrition please move to Close. The cow may start produce Colostrum.', 'لتحضير الحيوان لولادة صحية وتوفير تغذية أفضل، الرجاء نقلها إلى مرحلة الإغلاق. قد تبدأ البقرة بإنتاج اللبأ.', 'TagNumber', 'Pregnant', '21 Days  before Due Date',
  NULL, 'SYSTEM', 'HIGH', NULL, NULL, ARRAY['IN_APP', 'PUSH'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '98de2440-2fc6-5ed3-b28f-a649b787d8af', 90, 'Milk', NULL, 'CATTLE', NULL, NULL,
  NULL, 'Lactation Updated', NULL, 'تم تحديث دورة الحليب',
  'Lactation is updated to Cow Fresh', 'تم تحديث دورة الحليب إلى بقرة طازجة', 'TagNumber', 'Birth', 'Day of Birth',
  NULL, 'SYSTEM', 'LOW', NULL, NULL, ARRAY['IN_APP'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  '2748ce89-a4bb-5d9b-8a8d-67182c29b299', 91, 'Milk', NULL, 'CATTLE', NULL, NULL,
  NULL, 'Lactation Updated', NULL, 'تم تحديث دورة الحليب',
  'Lacation is updated to Cow Early Lactation', 'تم تحديث دورة الحليب إلى بداية الحليب', 'TagNumber', 'Birth', '2 months after animal has given birth',
  NULL, 'SYSTEM', 'LOW', NULL, NULL, ARRAY['IN_APP'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  'b3259073-ffa0-5a05-8bb8-21d9895af4ed', 92, 'Milk', NULL, 'CATTLE', NULL, NULL,
  NULL, 'Lactation Updated', NULL, 'تم تحديث دورة الحليب',
  'Lacation is updated to  Cow Mid Lactation', 'تم تحديث دورة الحليب إلى منتصف فترة الحليب', 'TagNumber', 'Birth', '3 months after animal has given birth',
  NULL, 'SYSTEM', 'LOW', NULL, NULL, ARRAY['IN_APP'],
  TRUE, TRUE, TRUE, NULL
);
INSERT INTO notification_task_definitions (
  id, task_id, category, country_code, species, current_state, source,
  notification_text, task_name, notification_text_ar, task_name_ar,
  expanded_detail, expanded_detail_ar, level, trigger_event, trigger_criteria,
  due_date_rule, action_by, priority, frequency, system_action, channels,
  go_live, is_active, default_enabled, notes
) VALUES (
  'aa9cc9ee-366d-56c3-83c5-4ca09216d442', 93, 'Milk', NULL, 'CATTLE', NULL, NULL,
  NULL, 'Lactation Updated', NULL, 'تم تحديث دورة الحليب',
  'Lactation is updated to Cow Late Lactation', 'تم تحديث دورة الحليب إلى نهاية فترة الحليب', 'TagNumber', 'Birth', '4 months after animal has given birth',
  NULL, 'SYSTEM', 'LOW', NULL, NULL, ARRAY['IN_APP'],
  TRUE, TRUE, TRUE, NULL
);
